spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: matdata-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

tenant:
  enabled: false
server:
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB
